### ISSUE TITLE
One module to support two OOS versions

### ISSUE THREAD

**Issue by zehuanli** [zehuanli/Oneplus-No-Red-One#3]
This module now supports OOS 12 due to #2. However, hooks in `ClockStyleOp` and  `ClockStyleOp12` are both loaded regardless of the system version. Although one of them will eventually run into an exception of not finding the corresponding app to inject and die, there could be a better design to support both versions elegantly.

**Comment by pkejval** [comment]
Can you please release new version with OOS 12 support? I don't know how to compile app myself. Thank you!

**Comment by zehuanli** [comment]
Done f6912037005a8b7123fe7907cfc2c81db191bed8
