### ISSUE TITLE
OOS 13 Compatibility

### ISSUE THREAD

**Issue by oceangith** [zehuanli/Oneplus-No-Red-One#4]

**Comment by zehuanli** [comment]
My phone just got switched to OOS 12, while OOS 13 is still in closed Beta for my model, so I won't be able to work on this until it's released.

**Comment by deathline94** [comment]
now would be an amazing time for an update as in OOS13 is finally published

**Comment by zehuanli** [comment]
I just updated my phone to OOS 13, WIP.

**Comment by zehuanli** [comment]
Done 9076522bb0c2040607ecbfc4b8692cfe05dce504

**Comment by zehuanli** [comment]
Done 2e9940a5c151ee60243808dd0284aa28e6dffb17
