### ISSUE TITLE
一加9RT OOS A11 11.3 不生效

### ISSUE THREAD

**Issue by cantonadong** [zehuanli/Oneplus-No-Red-One#6]
最新版3.0
9RT OOS A11 11.3
LS 1.8.5 Zygisk
开启OPGO，关联：百变引擎、系统界面
无效，还是红色的1。

**Comment by zehuanli** [comment]
请问
1. 启用模组后是否重启了手机？
2. 2.2或更早版本是否生效？
3. 红色的1出现在AOD，锁屏，还是时钟插件上？

**Comment by cantonadong** [comment]
1. 重启了也不生效
2. 试了下2.1，也不行。
3. 锁屏、桌面的自带时间控件，都不生效。

**Comment by zehuanli** [comment]
可以的话请把你的`com.android.systemui`的apk上传一下（apk位置可以通过`pm path com.android.systemui`找到），我看看是不是OOS 11新版本的问题。
