### ISSUE TITLE
一加8PRO OOS13 F13 不生效

### ISSUE THREAD

**Issue by Costben** [zehuanli/Oneplus-No-Red-One#7]
最新版3.0
8PRO OOS13 F13
LS 1.8.6 Zygisk
作用域：百变引擎、SystemUI
AOD默认布局不生效，还是红1，其余都生效
[百变引擎_13.0.38.zip](https://github.com/zehuanli/Oneplus-No-Red-One/files/10471432/_13.0.38.zip)

**Comment by zehuanli** [comment]
抱歉来晚了。这个module对于星期在上时间在下的那个AOD确实不生效，因为在反编译时我测试不出其对应的类（我只用了静态反编译）。我有空再研究研究。

**Comment by zehuanli** [comment]
哥们还在用OOS13吗，这个issue暂且先关了，如果有需要欢迎重新开
